version: "3.8"

services: 

  nginx:
    image: "nginx:latest"
    #container_name: nginx
    ports: 
      - 8001-8005:80
    volumes: 
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - php-fpm
    deploy:
      replicas: 2

  php-fpm:
    image: "lab4_php-fpm:latest"
    #build: .
    container_name: php-fpm
    volumes:
      - ./html:/usr/share/nginx/html

  mysql:
    image: "mysql:latest"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
