version: "3.8"

services: 

  nginx:
    image: "nginx:latest"
    container_name: nginx
    ports: 
      - 80:80
    volumes: 
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - php-fpm

  php-fpm:
    image: "php:7.4-fpm"
    container_name: php-fpm
    volumes:
      - ./html:/usr/share/nginx/html