version: "3.8"

services: 

  nginx:
    image: "nginx:latest"
    #container_name: nginx
    ports: 
      - 8001-8002:80
    volumes: 
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - php-fpm
    environment:
      TZ: Europe/Moscow
    deploy:
      replicas: 2

  php-fpm:
    #image: "lab4_php-fpm:latest"
    build: .
    container_name: php-fpm
    volumes:
      - ./html:/usr/share/nginx/html

  mysql:
    image: "mysql:latest"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: register
    command: --init-file /data/application/init.sql
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/init.sql:/data/application/init.sql